apiVersion: apps/v1
kind: Deployment
metadata:
  name: points
  labels:
    app: points
spec:
  replicas: 1
  selector:
    matchLabels:
      app: points
  template:
    metadata:
      labels:
        app: points
    spec:
      containers:
        - name: points
          image: "username/points:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
